server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    com.dush.springcloud_learning.microservice_consumer_movie_feign.study.user.feign.UserFeignClient: DEBUG